version: '3.9'

services:
  pg_master:
    build: ./master
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: unless-stopped

  pg_replica:
    build: ./replica
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    depends_on:
      - pg_master
    restart: unless-stopped
