services:
  pg_master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./master/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./master/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./master/init-replica-user.sql:/docker-entrypoint-initdb.d/init-replica-user.sql
    restart: unless-stopped

  pg_replica:
    image: postgres:15
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    depends_on:
      - pg_master
    volumes:
      - ./replica/data:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./replica/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
