version: '3.9'

services:
  pg_master:
    build: ./master
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
    restart: unless-stopped

  pg_replica:
    build: ./replica
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    depends_on:
      - pg_master
    volumes:
      - replica_data:/var/lib/postgresql/data
    user: 999:999
    restart: unless-stopped

volumes:
  master_data:
  replica_data:
