services:
  pg_master:
    image: postgres:15
    container_name: pg_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./master/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./master/init-replica-user.sql:/docker-entrypoint-initdb.d/init-replica-user.sql
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf"
    ]
    restart: unless-stopped

  pg_replica:
    image: postgres:15
    container_name: pg_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    depends_on:
      - pg_master
    volumes:
      - ./replica/replica-data:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./replica/entrypoint.sh:/entrypoint.sh
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf"
    ]
    entrypoint: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
    restart: unless-stopped
